# LICENSE HEADER MANAGED BY add-license-header
#
# SPDX-FileCopyrightText: 2026 Ting-An Cheng
# SPDX-License-Identifier: MIT
#

"""Adapter for pyuvm functional coverage (External/Open-source environment)."""

import logging
import re
from pathlib import Path

from ..interface import CoverageTool
from ..models import CoverageDB

logger = logging.getLogger(__name__)

# Matches common coverage reporting patterns in logs:
#   "Functional Coverage: 85.5%"
#   "Total Coverage: 90.00 %"
#   "UVMCoverage: 77.2 %"
_PYUVM_COV_RE = re.compile(
    r"(?:functional\s+coverage|total\s+coverage|uvmcoverage)"
    r"[^\d]*(\d+(?:\.\d+)?)\s*%",
    re.IGNORECASE,
)


class PyuvmCoverageAdapter(CoverageTool):
    """Coverage adapter for pyuvm (External environment).

    Parses text-based coverage reports or logs generated by pyuvm testbenches
    using tools like cocotb-coverage or custom UVMCoverage subscribers.
    """

    def __init__(
        self,
        default_report_path: str = "coverage.txt",
    ) -> None:
        """Initialize the pyuvm coverage adapter.

        Args:
            default_report_path: Default file to parse if no job-specific
                report is found.

        """
        self.default_report_path = default_report_path

    def get_coverage(self, job_id: str) -> CoverageDB:
        """Retrieve coverage results for a specific pyuvm job.

        Args:
            job_id: The ID of the simulation job.  Looks for a log or report
                file named ``sim_{job_id}.log`` or the default report path.

        """
        # Try job-specific log first, then fallback to default report
        possible_paths = [
            Path(f"sim_{job_id}.log"),
            Path(self.default_report_path),
        ]

        for path in possible_paths:
            if path.exists():
                logger.info("Parsing pyuvm coverage from %s", path)
                try:
                    content = path.read_text()
                    pct = self._parse_total(content)
                    if pct is not None:
                        return CoverageDB(path=str(path), overall_percentage=pct)
                except Exception:
                    logger.exception("Failed to read coverage file: %s", path)

        logger.warning("No coverage report found for job_id: %s", job_id)
        return CoverageDB(path="", overall_percentage=0.0)

    def _parse_total(self, output: str) -> float | None:
        """Extract the total coverage percentage from the output string."""
        match = _PYUVM_COV_RE.search(output)
        if match:
            return float(match.group(1))
        return None
